# Generated by Django 4.0.4 on 2022-05-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lineup',
            fields=[
                ('idLine', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del line up')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo del line up')),
                ('mapa', models.CharField(max_length=30, verbose_name='Mapa del line up')),
                ('bando', models.CharField(max_length=3, verbose_name='Bando del line up')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del line up')),
                ('incorporacion', models.CharField(max_length=200, verbose_name='Fecha de incorporacion del line up')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LineApp.usuario')),
            ],
        ),
    ]
