# Generated by Django 4.0.4 on 2022-06-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del comentario')),
                ('comen', models.CharField(max_length=200, verbose_name='Comentario para el line up')),
                ('lineUp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LineApp.lineup')),
            ],
        ),
    ]
