# Generated by Django 4.0.4 on 2022-05-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0002_lineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to='avatars', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='incorporacion',
            field=models.CharField(max_length=200, verbose_name='Incorporacion del line up'),
        ),
    ]
