# Generated by Django 4.0.4 on 2022-05-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0003_usuario_foto_alter_lineup_incorporacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='agente',
            field=models.CharField(default=1, max_length=30, verbose_name='Agente del line up'),
            preserve_default=False,
        ),
    ]
