# Generated by Django 4.0.4 on 2022-05-31 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LineApp', '0004_lineup_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='usuario',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
