# Generated by Django 4.0.4 on 2022-06-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LineApp', '0004_alter_avatar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Dislikes del line up'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Likes del line up'),
        ),
    ]
